### PR TITLE
Updgrade lodash version

### PR DESCRIPTION
**Pull request by serenahathi**
This PR fixes the issue raised here: https://github.com/spmjs/node-scp2/issues/116.

### CODE REVIEW

**Comment by bfnagle** [comment]
Glad to see someone else is looking at the same vulnerability and working to push a fix.
Is there anything we can do to merge this update?

**Comment by bfnagle** [comment]
Seems like there hasn't been an update for 2 years, which isn't ideal...
https://www.npmjs.com/package/scp2

**Comment by bfnagle** [comment]
Are there plans to publish this commit to npm?
https://www.npmjs.com/package/scp2
@lepture @popomore

**Comment by rramanadham** [comment]
Can someone publish the latest commit fixing the lodash version (#123 ) to npm?

**Comment by dawn-chu** [comment]
Can someone publish this change?

**Comment by walliby** [comment]
> This PR fixes the issue raised here: #116.

Looks like these last few changes just needs to be published to npm. Any help with this? @serenahathi @lepture @popomore

**Pull request merged**
