### PR TITLE
fix: scp from windows client with folder

### PR DESCRIPTION
**Pull request by xujihui1985**
when scp from widows machine with folder, permisson is 16822 which
is not same as linux like 0755

### CODE REVIEW

**Comment by lepture** [comment]
ping @afc163 @popomore

**Comment by afc163** [comment]
+1

**Comment by lepture** [comment]
@afc163 you can publish it.

**Comment by popomore** [comment]
@lepture ONLY you can publish it.

**Comment by popomore** [comment]
+ scp2@0.3.0

**Pull request merged**
